### ISSUE TITLE
data files for on-the-fly transformations missing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/binder-notebook#13]
The notebook [transformations/on-the-fly-transformations.ipynb](https://github.com/MDAnalysis/binder-notebook/blob/master/notebooks/transformations/on-the-fly-transformations.ipynb) (open in [nbviewer](https://nbviewer.jupyter.org/github/MDAnalysis/binder-notebook/blob/master/notebooks/transformations/on-the-fly-transformations.ipynb)) (which was added in PR #10 ) uses 
```python
u = mda.Universe('pept_in_memb.tpr', 'pept_in_memb.xtc')
```
These files `pept_in_memb.tpr', 'pept_in_memb.xtc'` are not installed with binder so the notebook will not run on binder. All notebooks should be fully self-contained.

Possible solutions:
- add these files in MDAnalysisTests or replace with files in MDAnalysisTests
- add these files to https://github.com/MDAnalysis/MDAnalysisData and install MDAnalysisData as part of our binder set up

**Comment by orbeckst** [comment]
@davidercruz can you please comment on this issue? How big are the files that you used for the example or are they already in MDAnalysisTests?

**Comment by davidercruz** [comment]
Hi @orbeckst, sorry for the late response.
The files are really small - about 250KB each. Where do I upload them?

**Comment by orbeckst** [comment]
Can you please provide a very brief description of the trajectory? I am trying to decide if they are better suited for MDAnalysisData than the tests. 

- What kind of system?
- How many frames?
- How many atoms?
- water included?
- Is anything interesting happening in the simulations?
- Can or should they be used to test the transformation features?

@jbarnoud your opinion is also welcome!

**Comment by davidercruz** [comment]
It's a 19 residue peptide embeded in a 128 DMPC membrane, without water molecules. The trajectory has 10 frames, 6085 atoms. It's a simple systems that I put together for the notebook, as I found it more interesting in the context of some of the on-the-fly transformations. It could be used in the tests, although I managed to do the tests with the existing test data.

**Comment by orbeckst** [comment]
Given that the tests don't require it, it sounds like a useful system for MDAnalysisData – small membrane system, stuff moving across boundaries, simple peptides and lipids. *Would you be willing to share an extended version of the trajectory under a suitable open licence?*  Along the lines of
- include water
- 50 - 500 frames (at a suitable time step to have peptide cross boundaries)
- keeping size < 100 MB (adjust frames accordingly)  – smaller is better

This would be a really good system to have available. We currently don't have anything with water + lipids + protein.

They way to make these available is to dump the files (TPR and XTC) on figshare. As an example see 
https://figshare.com/articles/Molecular_dynamics_trajectory_of_membrane_protein_NhaA/7185203/2
I will then add the data set to the [available data sets](https://www.mdanalysis.org/MDAnalysisData/usage.html) or if you want to do the PR, I'll tell you what to do.

Once this is done, I'll add MDAnalysisData to the binder repo.

**Comment by orbeckst** [comment]
@davidercruz if creating the more extended trajectory is too much work then could you please nevertheless put your original trajectory on figshare? You are the author of the files so you have to do it and decide on a license. Thanks.

**Comment by orbeckst** [comment]
ping @davidercruz

**Comment by orbeckst** [comment]
@jbarnoud @mnmelo do you happen to have access to the file that @davidercruz has used here, or can you get in touch with him?

**Comment by davidercruz** [comment]
Hi, sorry for being MIA. Here are the files:
https://figshare.com/articles/Short_molecular_dynamics_of_a_peptide_inside_a_pure_DMPC_membrane/8046437

**Comment by orbeckst** [comment]
Awesome! Many thanks.

I'll ~open~ update  the issue for MDAData (https://github.com/MDAnalysis/MDAnalysisData/issues/34).

**Comment by orbeckst** [comment]
We now have a 0.7.0 release of MDAnalysisData that contains the new [Membrane peptide dataset](https://www.mdanalysis.org/MDAnalysisData/membrane_peptide.html). Once the conda package has been built, we can add it to the binder setup file [environment.yml](https://github.com/MDAnalysis/binder-notebook/blob/master/environment.yml) and update the notebook.
